# Generated by Django 2.1.2 on 2018-11-28 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0016_auto_20181128_1931'),
        ('producto', '0009_auto_20181122_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traslados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('enviada', models.BooleanField(default=False)),
                ('despachada', models.BooleanField(default=False)),
                ('autorizada', models.BooleanField(default=False)),
                ('lista', models.ManyToManyField(to='producto.Codigo')),
                ('tienda_recibe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tienda_recibe', to='usuario.Tienda')),
                ('tienda_solicita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tienda_solicita', to='usuario.Tienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Usuario')),
            ],
        ),
    ]
