# Generated by Django 2.1.2 on 2018-11-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traslado', '0002_auto_20181128_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traslados',
            name='despacha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despachada', to='usuario.Usuario'),
        ),
    ]
