# Generated by Django 2.1.2 on 2018-12-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traslado', '0003_auto_20181130_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traslados',
            name='autorizada',
        ),
        migrations.RemoveField(
            model_name='traslados',
            name='despachada',
        ),
    ]
