# Generated by Django 2.1.2 on 2018-12-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado', '0004_auto_20181201_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='traslados',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
