# Generated by Django 2.1.2 on 2018-10-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_tienda_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='crear_marca',
            field=models.BooleanField(default=False),
        ),
    ]
