# Generated by Django 2.1.2 on 2018-10-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_crear_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='crear_producto',
            field=models.BooleanField(default=False),
        ),
    ]
