# Generated by Django 2.1.2 on 2018-10-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_crear_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='combinar_productos',
            field=models.BooleanField(default=False),
        ),
    ]
