# Generated by Django 2.1.2 on 2018-11-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_combinar_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargar_compra',
            field=models.BooleanField(default=False),
        ),
    ]
