# Generated by Django 2.1.2 on 2018-11-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_usuario_orden_de_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='crear_clientes',
            field=models.BooleanField(default=False),
        ),
    ]
