# Generated by Django 2.1.2 on 2018-11-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_usuario_crear_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='historial_clientes',
            field=models.BooleanField(default=False),
        ),
    ]
