# Generated by Django 2.1.2 on 2018-11-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_usuario_historial_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modificar_clientes',
            field=models.BooleanField(default=False),
        ),
    ]
