# Generated by Django 2.1.2 on 2018-11-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_usuario_crear_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autorizar_orden',
            field=models.BooleanField(default=False),
        ),
    ]
