# Generated by Django 2.1.2 on 2018-11-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_usuario_autorizar_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='inventario',
            field=models.BooleanField(default=False),
        ),
    ]
