# Generated by Django 2.1.2 on 2018-11-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_usuario_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ver_costos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_distribuidor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_efectivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_mayorista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ver_tarjeta',
            field=models.BooleanField(default=False),
        ),
    ]
