# Generated by Django 2.1.2 on 2018-11-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_usuario_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autorizar_traslados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='solicitar_traslados',
            field=models.BooleanField(default=False),
        ),
    ]
