# Generated by Django 2.1.2 on 2018-12-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_tienda_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='listar_traslados',
            field=models.BooleanField(default=False),
        ),
    ]
