# Generated by Django 2.1.2 on 2018-11-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20181114_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
