# Generated by Django 2.1.2 on 2018-11-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20181115_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
