# Generated by Django 2.1.2 on 2018-11-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0010_usuario_modificar_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('dias', models.IntegerField()),
                ('atiende', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nit', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('dias', models.IntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='persona.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Tienda'),
        ),
    ]
