# Generated by Django 2.1.2 on 2018-11-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_usuario_crear_proveedor'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Tienda'),
            preserve_default=False,
        ),
    ]
