# Generated by Django 2.1.2 on 2018-11-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_proveedor_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dias',
            field=models.IntegerField(default=0),
        ),
    ]
