# Generated by Django 2.1.2 on 2018-11-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20181119_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='dias',
            field=models.IntegerField(default=0),
        ),
    ]
