# Generated by Django 2.1.2 on 2018-11-26 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20181119_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='atiende',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Usuario'),
        ),
    ]
