# Generated by Django 2.1.2 on 2018-11-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0003_codigo'),
        ('usuario', '0011_usuario_crear_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_de_compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('autorizacion', models.BooleanField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('autoriza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='autoriza', to='usuario.Usuario')),
                ('listado', models.ManyToManyField(to='producto.Codigo')),
                ('solicita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicita', to='usuario.Usuario')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Tienda')),
            ],
        ),
    ]
