# Generated by Django 2.1.2 on 2018-11-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_usuario_crear_proveedor'),
        ('persona', '0002_proveedor_tienda'),
        ('producto', '0004_auto_20181114_2021'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('documento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('credito', models.BooleanField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('listado', models.ManyToManyField(to='producto.Codigo')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Tienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizacion', models.BooleanField()),
                ('autoriza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='autoriza_compra', to='usuario.Usuario')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Historial')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='persona.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('autorizacion', models.BooleanField()),
                ('autoriza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='autoriza_venta', to='usuario.Usuario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='persona.Cliente')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Historial')),
            ],
        ),
        migrations.RemoveField(
            model_name='orden_de_compra',
            name='autoriza',
        ),
        migrations.RemoveField(
            model_name='orden_de_compra',
            name='listado',
        ),
        migrations.RemoveField(
            model_name='orden_de_compra',
            name='solicita',
        ),
        migrations.RemoveField(
            model_name='orden_de_compra',
            name='tienda',
        ),
        migrations.DeleteModel(
            name='Orden_de_compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.Orden'),
        ),
    ]
