# Generated by Django 2.1.2 on 2018-11-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20181114_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='hoja',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
