# Generated by Django 2.1.2 on 2018-11-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_orden_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='credito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='autorizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='autorizacion',
            field=models.BooleanField(default=False),
        ),
    ]
