# Generated by Django 2.1.2 on 2018-11-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20181115_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
