# Generated by Django 2.1.2 on 2018-11-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_orden_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='hoja',
        ),
        migrations.AddField(
            model_name='historial',
            name='hoja',
            field=models.IntegerField(default=0),
        ),
    ]
