# Generated by Django 2.1.2 on 2018-11-27 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_auto_20181126_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='autoriza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autoriza_venta', to='usuario.Usuario'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='persona.Cliente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.Venta'),
        ),
    ]
