# Generated by Django 2.1.2 on 2018-11-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_auto_20181127_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='envio',
            field=models.BooleanField(default=False),
        ),
    ]
