# Generated by Django 2.1.2 on 2018-11-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_venta_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='osbservacion',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
